=== dainst/cilantro/test/e2e/schema/run_job_param_ingest_journal.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Cilantro Upload Param v1",
  "definitions": {
    "file_and_range": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "file": {
          "type": "string"
        },
        "range": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "maxItems": 2,
          "minItems": 2
        }
      },
      "required": [
        "file",
        "range"
      ]
    },
    "article_and_params": {
      "type": "object",
      "required": ["metadata", "create_frontpage", "files" ],
      "properties": {
        "metadata": {
          "type": "object",
          "required": ["title", "author", "pages", "date_published", "language"],
          "properties": {
            "title": {"type": "string"},
            "author": {
              "type": "array",
              "items": {"$ref": "#/definitions/author"}
            },
            "pages": {"$ref": "#/definitions/pages"},
            "date_published": {
              "type": "string",
              "pattern": "[0-9]{4}-[0-9]{0,2}-[0-9]{0,2}$"
            },
            "language": {
              "type": "string",
              "pattern": "^[a-z]{2}_[A-Z]{2}$"
            },
            "zenonId": {"type": "string"}
          }
        },
        "files": {
          "type": "array",
          "items": {
            "anyOf": [
              {"$ref": "#/definitions/file_and_range"},
              {"type": "string"}
            ]
          }
        },
        "auto_publish": {"type": "boolean"},
        "create_frontpage": {"type": "boolean"}
      }
    },
    "author": {
      "type": "object",
      "required": ["lastname"],
      "additionalProperties": false,
      "properties": {
        "firstname": {"type": "string"},
        "lastname": {"type": "string"}
      }
    },
    "pages": {
      "type": "object",
      "required": ["startPrint", "endPrint", "showndesc"],
      "additionalProperties": false,
      "properties": {
        "showndesc": {"type": "string"},
        "startPrint": {"type": "number"},
        "endPrint": {"type": "number"}
      }
    }
  },
  "type": "object",
  "required": [
    "metadata"
  ],
  "properties": {
    "metadata": {
      "type": "object"
    },
    "files": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/file_and_range"
          },
          {
            "type": "string"
          }
        ]
      }
    },
    "parts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/article_and_params"
      }
    },
    "ojs_journal_code": {"type": "string"},
    "ojs_user": {"type": "string"},
    "auto_publish_issue": {"type": "boolean"},
    "default_publish_articles": {"type": "boolean"},
    "default_create_frontpage": {"type": "boolean"},
    "allow_upload_without_file": {"type": "boolean"}
  }
}

=== dainst/cilantro/frontend/test/e2e/resources/schema/example/run_job_param.json
{
  "metadata": {
    "volume": "",
    "year": 2018,
    "number": "",
    "description": "[PDFs teilweise verfügbar]",
    "importFilePath": "e2e-testing.pdf",
    "identification": "year"
  },
  "files": [
    "e2e-testing.pdf",
    "e2e-testing_2.pdf"
  ],
  "parts": [
    {
      "metadata": {
        "title": "Ein kleines Musterdokument mit zweizeiligem Titel",
        "abstract": "Bachelorarbeit",
        "author": [
          {
            "firstname": "Erich ",
            "lastname": "Mustermann"
          }
        ],
        "pages": {
          "showndesc": "1–20",
          "startPrint": 1,
          "endPrint": 20
        },
        "date_published": "2018--",
        "language": "de_DE",
        "zenonId": ""
      },
      "files": [
        {
          "file": "e2e-testing.pdf",
          "range": [
            1,
            20
          ]
        },
        {
          "file": "e2e-testing_2.pdf",
          "range": [
            1,
            22
          ]
        }
      ],
      "auto_publish": true,
      "create_frontpage": false
    },
    {
      "metadata": {
        "title": "Titel 2",
        "author": [
          {
            "firstname": "Autor",
            "lastname": "Dererste"
          }
        ],
        "pages": {
          "showndesc": "21–27",
          "startPrint": 21,
          "endPrint": 27
        },
        "date_published": "2018--",
        "language": "de_DE",
        "zenonId": ""
      },
      "files": [
        {
          "file": "e2e-testing.pdf",
          "range": [
            21,
            6
          ]
        },
        "e2e-testing_2.pdf"
      ],
      "auto_publish": true,
      "create_frontpage": false
    }
  ],
  "ojs_journal_code": "aa",
  "ojs_user": "ojs_user",
  "auto_publish_issue": false,
  "default_publish_articles": true,
  "default_create_frontpage": true,
  "allow_upload_without_file": false
}
